### ISSUE TITLE
Install CDK

### ISSUE THREAD

**Issue by nabarunchakma** [Ramrachai/indigenous-connect-infrastructure#1]
This issue is to install CDK on local machine.  CDK will be required only for Infrastructure Developers.

The instruction on how to install CDK.

https://docs.aws.amazon.com/cdk/v2/guide/getting_started.html

**Comment by nabarunchakma** [comment]
@Ramrachai  This is for you to action.

**Comment by Ramrachai** [comment]
cdk installation is done in my local machine.
